[package]
name = "diario_tarefas"
version = "0.1.0"
edition = "2021"


[dependencies]
rocket = "0.5"
mysql = "26.0.0"
serde = { version = "1.0", features = ["derive"] }
rocket_dyn_templates = { version = "0.2.0", features = ["handlebars"] }
